Device fields #25
spark/spark-sdk-android pull request #35
Opened 2017-02-10 17:34 UTC by CityVibes

Adding missing fields that now are visible in getDevice response.
Also updated example app to include separate activity which will display device information.

@jensck SimpleDevice and CompleteDevice now has even more parameters in constructor, any suggestions? Perhaps build pattern would make some sense?

2017-02-10 18:51 UTC, jensck requested changes
Need to accommodate the `Parcelable` stuff (if you can't see them: github is calling the comments "outdated" because I put the comments on the commit level rather than that final files)

Also yes, I agree: a builder would be a really good idea, particularly now that we have multiple fields of the same type, one right after the other.

2017-02-10 18:51 UTC, jensck commented on cloudsdk/src/main/java/io/particle/android/sdk/cloud/DeviceState.java
> +        dest.writeString(ipAddress);
Are these nullable fields?  If so, we should be using `writeValue()` and `readValue()`.

2017-02-10 18:51 UTC, jensck commented on cloudsdk/src/main/java/io/particle/android/sdk/cloud/DeviceState.java
> +        dest.writeString(imei);
Same thing here as elsewhere: if these are nullable, we should be using `read/writeValue()`

2017-02-10 18:51 UTC, jensck commented on cloudsdk/src/main/java/io/particle/android/sdk/cloud/DeviceState.java
> +    final boolean cellular;
if these are nullable (and I bet they are, e.g.: IMEI on a Photon), the fields should be marked as such

2017-02-10 18:51 UTC, jensck commented on cloudsdk/src/main/java/io/particle/android/sdk/cloud/DeviceState.java
> +        dest.writeString(imei);
Looks like I did that wrong on the `version` field, too.  Might be worth looking for all the nullable fields on these parcelables and applying `read/writeValue()` as needed.

2017-02-10 19:29 UTC, CityVibes commented
@jensck Not sure which fields are nullable though, pretty much every field could be depending on Api, right?

2017-02-13 19:14 UTC, jensck commented
@CityVibes technically, yes...  ugh.  Yeah, it's probably worth doing that for every object field. :(

It's not an issue ATM, but it should be fixed soon.  If you want, you can just file an issue on it and fix it on another PR.

2017-02-13 19:16 UTC, jensck approved these changes

2017-02-13 19:17 UTC, jensck commented
@CityVibes If you want to do the null handling or adding a builder here, go for it; if you want to do them on other PRs and merge what's here now, I'm fine with that, too.

2017-02-15 10:49 UTC, merged