Device types
spark/spark-sdk-android pull request #37
Opened 2017-02-21 21:41 UTC by CityVibes

Added more device types as per #20 issue.

2017-02-21 21:43 UTC, idokleinman approved these changes

2017-02-21 21:47 UTC, idokleinman requested changes

2017-02-21 21:47 UTC, idokleinman commented on cloudsdk/src/main/java/io/particle/android/sdk/cloud/ParticleDevice.java
>                  case 5:
5 is not a Photon/P0 platform ID, it's only 6 AFAIK

2017-02-21 21:57 UTC, towynlin commented on cloudsdk/src/main/java/io/particle/android/sdk/cloud/ParticleDevice.java
>                  case 5:
6 only

2017-02-21 22:28 UTC, CityVibes commented on cloudsdk/src/main/java/io/particle/android/sdk/cloud/ParticleDevice.java
>                  case 5:
What is 5 then?

2017-02-23 17:13 UTC, jensck approved these changes
LGTM

2017-02-27 21:15 UTC, idokleinman commented on cloudsdk/src/main/java/io/particle/android/sdk/cloud/ParticleDevice.java
>                  case 5:
Nothing :)

2017-02-28 16:48 UTC, CityVibes commented on cloudsdk/src/main/java/io/particle/android/sdk/cloud/ParticleDevice.java
>                  case 5:
@idokleinman Removed it.

2017-03-23 19:29 UTC, CityVibes commented
@idokleinman Any changes to do, or can I merge it?

2017-03-30 02:23 UTC, idokleinman approved these changes

2017-03-30 17:44 UTC, merged