Global listeners
spark/spark-sdk-android pull request #38
Opened 2017-02-22 11:27 UTC by CityVibes

As per #22 tried to implement global listener for system events. Went EventBus route. Not auto-subscribing, a.k.a user has to subscribe or unsubscribe to ParticleDevice system events by himself.

2017-02-22 18:18 UTC, CityVibes commented
Removed resetFlashingState, flashing state should change by listening to flashing system events now. Added local method for unsubscription by event handler for convenience (perhaps we should expose something like that to users?).

2017-02-24 00:28 UTC, jensck requested changes
Besides the few minor adjustments I recommended, I want to discuss the EventBus impl of this PR.

Though we want to avoid 3rd party dependencies in general, I'm OK with EventBus -- it's a solid library, and fairly lightweight.

However, it appears that this PR makes EventBus _part of our public API_, which is a much higher bar to clear.  It's a good lib, but I strongly recommend against tying ourselves to it that much unless there's an _overwhelming_ reason to do so, which I'm not seeing here.

Couldn't this be implemented using `LocalBroadcastManager` just as easily?  Or something which uses EventBus internally, but exposes an API that we control?

2017-02-24 00:28 UTC, jensck commented on cloudsdk/src/main/java/io/particle/android/sdk/cloud/ParticleEventHandler.java
> +public interface ParticleEventHandler extends SimpleParticleEventHandler {
You should probably remove the duplicated `onEvent()` method here

2017-02-24 00:28 UTC, jensck commented on cloudsdk/src/main/java/io/particle/android/sdk/cloud/ParticleDevice.java
> +    public void subscribeToSystemEvents() throws ParticleCloudException {
Since this is mutating a collection, you should at least annotate this `@MainThread` (and consider using `CopyOnWriteArrayList` anyhow)

2017-02-24 00:28 UTC, jensck commented on cloudsdk/src/main/java/io/particle/android/sdk/cloud/ParticleDevice.java
> +                    if (particleEvent.dataPayload.equals("success")) {
might want to do this the other way 'round, given how many things are permitted be null. :(  `"success".equals(...)`

2017-02-24 00:28 UTC, jensck commented on cloudsdk/src/main/java/io/particle/android/sdk/cloud/ParticleDevice.java
> +    private void unsubscribeFromEvents(SimpleParticleEventHandler handler) throws ParticleCloudException {
does this really need its own method + javadoc? ;)

2017-02-24 00:28 UTC, jensck commented on cloudsdk/src/main/java/io/particle/android/sdk/cloud/EventsDelegate.java
> +            for (int i = 0; i < eventReaders.size(); i++) {
you can use `eventReaders.indexOfValue()` to simplify this

2017-02-26 16:17 UTC, CityVibes commented on cloudsdk/src/main/java/io/particle/android/sdk/cloud/EventsDelegate.java
> +            for (int i = 0; i < eventReaders.size(); i++) {
Not exactly sure what are you suggesting here. IndexOfValue would require EventReader which I don't have thus I am looping through a whole list of EventReaders.

2017-02-26 16:31 UTC, CityVibes commented
@jensck I could probably tweak current LocalBroadcastManager implementation to also send system event updates, but for the most part I would like to keep EventBus as it is or remove it all together, as you mentioned it is solid and fairly lightweight library.

2017-02-27 21:19 UTC, idokleinman commented
Just to understand - a user must issue some command to subscribe to system events PER device instance? If so, what's the reasoning behind this decision?

2017-02-27 21:20 UTC, idokleinman reviewed
Just to understand - a user needs to issue some sort of command to subscribe to the system events PER device instance?
If so, what's the reasoning behind such a decision?

2017-02-27 21:29 UTC, CityVibes commented
Yep user subscribes to the system events per device. Other option could be subscribing to all system events for all devices automatically or manually, but that could result in a lot of events being sent at once if device count is high (for all we know user might care about one device at that time, right?). Giving user ability to manually subscribe/unsubscribe per device would be flexible and leave further implementation up to them.

2017-02-28 05:29 UTC, jensck approved these changes
Looks good from my end.

2017-02-28 05:29 UTC, jensck commented on cloudsdk/src/main/java/io/particle/android/sdk/cloud/ParticleDevice.java
> +        UNKNOWN
+1

2017-03-20 15:58 UTC, merged